apiVersion: v1beta3
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: web
        image: plecuyer/wordpress:1.7.9
        ports:
        - containerPort: 80
        env:
          - name: DB_PASSWORD
            value: "password"
          - name: DB_HOST
            value: "127.0.0.1"
          - name: DB_USER
            value: "wordpress"
          - name: DB_NAME
            value: "wordpress"
      - name: db
        image: mysql
        env:
          - name: MYSQL_PASSWORD
            value: "password"
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
          - name: MYSQL_USER
            value: "wordpress"
          - name: MYSQL_DATABASE
            value: "wordpress"